
#print_head "Build a package"
#mvn clean package &>>${LOG}
#Status_check
#
#print_head "Copy App file to App location"
#mv target/${component}-1.0.jar ${component}.jar &>>${LOG}
#Status_check
#
#SYSTEMD_SETUP
#
#LOAD_SCHEMA

- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Maven Build
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /app

- name: Copy App file to App location
  ansible.builtin.copy:
    src: target/{{component}}-1.0.jar
    dest: /app/{{component}}.jar
    remote_src: yes

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load