- name: Copy MongoDB Yum Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB server
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
#  community.mongodb.mongodb_shell:
#    login_host: mongodb-dev.devopschandra.online
#    file: "/app/schema/{{component}}.js"
  ansible.builtin.shell: mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.endpoint', region='us-east-1') }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.user', region='us-east-1') }} --password {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.pass', region='us-east-1') }} </app/schema/{{component}}.js
    idempotent: yes
