
- name: Install Python 3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Download Python Dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
  executable: pip3.6

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"



#  print_head "Install Python"
#  yum install python36 gcc python3-devel -y &>>${LOG}
#  Status_check
#
#  APP_PREREQ
#
#  print_head "Download Dependencies"
#  cd /app
#  pip3.6 install -r requirements.txt &>>${LOG}
#  Status_check
#
#  print_head "Update passwords in Service File"
#  sed -i -e "s/roboshop_rabbitmq_password/${roboshop_rabbitmq_password}/" ${script_location}/files/${component}.service &>>${LOG}
#  Status_check
#
#  SYSTEMD_SETUP


